version: '3.8'

services:
  event-flow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-flow-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./prisma:/app/prisma
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=file:/app/prisma/dev.db
